### ISSUE TITLE
SwayFX Fails to Build on Artix

### ISSUE THREAD

**Issue by cprin21** [WillPower3309/swayfx#270]
### Please fill out the following:
- **Swayfx Version:** 
- sway version 0.3.2

- **Description:**
  - Attempt to build swayfx on Artix Linux
  - Build fails due to libsystemd requirement during build time

**Comment by MrPenguin07** [comment]
I can build master on Gentoo without systemd.

Log file be helpful but I suspect this is a packaging issue.

**Comment by cprin21** [comment]
Yes, likely some weirdness going on with how it is packaged on the AUR. I will raise the issue on the AUR for the swayfx and swayfx-git packages instead of here.

**Comment by MrPenguin07** [comment]
> Yes, likely some weirdness going on with how it is packaged on the AUR. I will raise the issue on the AUR for the swayfx and swayfx-git packages instead of here.

Having taken a look inside the AUR package,
While systemd is not listed as a dependency - and for compilation it certainly isnt,
The file `50-systemd-user.conf` most certainly does require systemd;
```
# sway does not set DISPLAY/WAYLAND_DISPLAY in the systemd user environment
# See FS#63021
# Adapted from xorg's 50-systemd-user.sh, which achieves a similar goal.

# Upstream refuses to set XDG_CURRENT_DESKTOP so we have to.
exec systemctl --user set-environment XDG_CURRENT_DESKTOP=sway
exec systemctl --user import-environment DISPLAY \
                                         SWAYSOCK \
                                         WAYLAND_DISPLAY \
                                         XDG_CURRENT_DESKTOP
```

My suggestion to you would be to either edit this and instead use 
`exec dbus-update-activation-environment --all`
Then repackage it yourself, or remove it entirely or instead manually edit ~/.config/sway/config and add it there as that's what i've used on Gentoo without issue.

Since Erik is both the repo author and maintainer of AUR package, I do believe this issue could remain open as this could instead be an `if` statement to find if systemd is available, if not then change the command rather than erroring out.

Regards
