### ISSUE TITLE
Rebase to swaywm:master

### ISSUE THREAD

**Issue by ackstorm23** [WillPower3309/swayfx#67]
- **Rebase to swaywm:master for the latest bug fixes and improvements**

While I am excited for the new features swayfx brings, I am concerned with the growing list of commits you are behind on from swaywm. 

Will there be a regular cadence to catch up with bugs fixed in swaywm?

**Comment by Barbaross93** [comment]
Perhaps it deserves a mention in the README, but as @WillPower3309 has said in previous reddit threads, the reason you see so many commits behind upstream sway is because this fork is based on sway releases. As soon as sway 1.8 is released, the plan is to rebase this fork with 1.8.

**Comment by WillPower3309** [comment]
Thanks @Barbaross93 ! As mentioned, we'd like to remain stable while providing our new features. Having releases lined up with sway's greatly reduces ambiguity when debugging issues as well, as it's easier to see if it's caused by upstream since we have a release to compare to. I've had a few questions about this, so I think I'll add a bit to the readme about it!
